# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_router_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='router',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
