# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_server_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
